#!/usr/bin/env python3

from __future__ import annotations

from dataclasses import replace

from projects.core.dsl import execute_tasks, task, toolbox
from projects.llm_d.runtime import llmd_runtime, phase_inputs


def run(*, inputs_file: str) -> int:
    """
    Apply the llm_d DataScienceCluster manifest.

    Args:
        inputs_file: Path to the prepare phase input file generated by orchestration
    """

    llmd_runtime.init()
    execute_tasks(locals())
    return 0


@task
def load_inputs(args, ctx):
    """Load prepare inputs into the command-local artifact directory"""

    ctx.config = replace(
        phase_inputs.load_prepare_inputs(args.inputs_file),
        artifact_dir=args.artifact_dir,
    )
    return f"Loaded DataScienceCluster inputs for namespace {ctx.config.namespace}"


@task
def apply_datasciencecluster(args, ctx):
    """Render and apply the DataScienceCluster manifest"""

    config = ctx.config
    manifest = llmd_runtime.render_datasciencecluster(config)
    llmd_runtime.apply_manifest(config.artifact_dir / "src" / "datasciencecluster.yaml", manifest)
    llmd_runtime.oc(
        "get",
        "datasciencecluster",
        config.platform["rhoai"]["datasciencecluster_name"],
        "-n",
        config.platform["rhoai"]["namespace"],
        "-o",
        "yaml",
        capture_output=True,
    )
    return "DataScienceCluster applied"


main = toolbox.create_toolbox_main(run)


if __name__ == "__main__":
    main()
