#!/usr/bin/env python3

from __future__ import annotations

import json
import logging
from pathlib import Path

from projects.core.dsl import execute_tasks, shell, task, toolbox
from projects.llm_d.orchestration import llmd_runtime, phase_inputs
from projects.llm_d.toolbox.prepare_model_cache import main as prepare_model_cache

LOGGER = logging.getLogger(__name__)


def run(*, inputs_file: str) -> int:
    """Prepare a cluster for llm_d downstream smoke and benchmark runs.

    Args:
        inputs_file: Path to the prepare phase input file generated by orchestration
    """

    llmd_runtime.init()
    execute_tasks(locals())
    return 0


@task
def load_inputs(args, ctx):
    """Load the prepare phase inputs"""

    ctx.config = phase_inputs.load_prepare_inputs(args.inputs_file)
    return f"Loaded prepare inputs for preset {ctx.config.preset_name}"


@task
def verify_oc_access_task(args, ctx):
    """Verify OpenShift CLI access"""

    llmd_runtime.oc("whoami", capture_output=True)
    return "OpenShift CLI access verified"


@task
def verify_cluster_version_task(args, ctx):
    """Validate the cluster version against llm_d requirements"""

    version_info = llmd_runtime.oc("version", "-o", "json", capture_output=True)
    payload = json.loads(version_info.stdout)

    openshift_version = (
        payload.get("openshiftVersion")
        or payload.get("serverVersion", {}).get("gitVersion")
        or payload.get("serverVersion", {}).get("platform")
    )
    if not openshift_version:
        raise RuntimeError("Could not determine OpenShift version from `oc version -o json`")

    minimum = ctx.config.platform["cluster"]["minimum_openshift_version"]
    if llmd_runtime.version_tuple(openshift_version) < llmd_runtime.version_tuple(minimum):
        raise RuntimeError(
            f"Cluster version {openshift_version} is older than the llm_d minimum {minimum}"
        )

    return f"Cluster version satisfies {minimum}"


@task
def prepare_cert_manager_task(args, ctx):
    """Ensure the cert-manager operator is installed"""

    operator_spec = llmd_runtime.operator_spec_by_package(
        ctx.config.platform, "openshift-cert-manager-operator"
    )
    ensure_operator_subscription(operator_spec)
    return "cert-manager operator ready"


@task
def prepare_leader_worker_set_task(args, ctx):
    """Ensure the leader-worker-set operator is installed"""

    operator_spec = llmd_runtime.operator_spec_by_package(ctx.config.platform, "leader-worker-set")
    ensure_operator_subscription(operator_spec)
    return "leader-worker-set operator ready"


@task
def prepare_nfd_task(args, ctx):
    """Ensure Node Feature Discovery is installed and reporting GPU labels"""

    config = ctx.config
    operator_spec = llmd_runtime.operator_spec_by_package(config.platform, "nfd")
    ensure_operator_subscription(operator_spec)
    llmd_runtime.wait_for_crd(
        operator_spec["bootstrap_crd"],
        timeout_seconds=operator_spec["wait_timeout_seconds"],
    )

    manifest = llmd_runtime.load_manifest_template(config, operator_spec["bootstrap_manifest"])
    nfd_name = manifest["metadata"]["name"]
    nfd_namespace = manifest["metadata"]["namespace"]
    if llmd_runtime.resource_exists("nodefeaturediscovery", nfd_name, namespace=nfd_namespace):
        LOGGER.info(
            "NodeFeatureDiscovery/%s already exists in %s; verifying GPU discovery labels",
            nfd_name,
            nfd_namespace,
        )
    else:
        llmd_runtime.apply_manifest(
            config.artifact_dir / "src" / "nfd-nodefeaturediscovery.yaml",
            manifest,
        )

    llmd_runtime.wait_until(
        "NodeFeatureDiscovery bootstrap resource",
        timeout_seconds=operator_spec["wait_timeout_seconds"],
        interval_seconds=10,
        predicate=lambda: llmd_runtime.resource_exists(
            "nodefeaturediscovery",
            nfd_name,
            namespace=nfd_namespace,
        ),
    )

    wait_for_nfd_gpu_labels(config, timeout_seconds=operator_spec["wait_timeout_seconds"])
    return "Node Feature Discovery ready"


@task
def prepare_gpu_operator_task(args, ctx):
    """Ensure the GPU operator is installed and ready"""

    config = ctx.config
    operator_spec = llmd_runtime.operator_spec_by_package(config.platform, "gpu-operator-certified")
    ensure_operator_subscription(operator_spec)
    llmd_runtime.wait_for_crd(
        operator_spec["bootstrap_crd"],
        timeout_seconds=operator_spec["wait_timeout_seconds"],
    )

    manifest = llmd_runtime.load_manifest_template(config, operator_spec["bootstrap_manifest"])
    clusterpolicy_name = manifest["metadata"]["name"]
    if llmd_runtime.resource_exists("clusterpolicy", clusterpolicy_name):
        LOGGER.info(
            "ClusterPolicy/%s already exists; verifying readiness instead of applying bootstrap manifest",
            clusterpolicy_name,
        )
    else:
        llmd_runtime.apply_manifest(
            config.artifact_dir / "src" / "gpu-clusterpolicy.yaml",
            manifest,
        )

    wait_for_gpu_clusterpolicy_ready(
        clusterpolicy_name,
        timeout_seconds=operator_spec["wait_timeout_seconds"],
    )
    return "GPU operator ready"


@task
def prepare_rhoai_operator_task(args, ctx):
    """Ensure the RHOAI operator is installed"""

    config = ctx.config
    operator_spec = llmd_runtime.operator_spec_by_package(config.platform, "rhods-operator")
    ensure_operator_subscription(operator_spec)
    for crd_name in config.platform["rhoai"]["required_crds_before_dsc"]:
        llmd_runtime.wait_for_crd(
            crd_name,
            timeout_seconds=config.platform["rhoai"]["wait_timeout_seconds"],
        )
    return "RHOAI operator ready"


@task
def apply_datasciencecluster_task(args, ctx):
    """Apply the DataScienceCluster manifest"""

    config = ctx.config
    manifest = llmd_runtime.render_datasciencecluster(config)
    llmd_runtime.apply_manifest(config.artifact_dir / "src" / "datasciencecluster.yaml", manifest)
    llmd_runtime.oc(
        "get",
        "datasciencecluster",
        config.platform["rhoai"]["datasciencecluster_name"],
        "-n",
        config.platform["rhoai"]["namespace"],
        "-o",
        "yaml",
        capture_output=True,
    )
    return "DataScienceCluster applied"


@task
def wait_for_datasciencecluster_ready_task(args, ctx):
    """Wait for the DataScienceCluster to become ready"""

    rhoai = ctx.config.platform["rhoai"]

    def _dsc_ready() -> bool:
        payload = llmd_runtime.oc_get_json(
            "datasciencecluster",
            name=rhoai["datasciencecluster_name"],
            namespace=rhoai["namespace"],
        )
        phase = payload.get("status", {}).get("phase")
        if phase == "Ready":
            return True
        if phase in {"Failed", "Error"}:
            raise RuntimeError(f"DataScienceCluster entered terminal phase {phase}")
        return False

    llmd_runtime.wait_until(
        f"datasciencecluster/{rhoai['datasciencecluster_name']} ready",
        timeout_seconds=rhoai["wait_timeout_seconds"],
        interval_seconds=10,
        predicate=_dsc_ready,
    )
    return "DataScienceCluster ready"


@task
def ensure_required_crds_task(args, ctx):
    """Wait for the llm_d-required CRDs to exist"""

    for crd_name in ctx.config.platform["rhoai"]["required_crds_after_dsc"]:
        llmd_runtime.wait_for_crd(
            crd_name,
            timeout_seconds=ctx.config.platform["rhoai"]["wait_timeout_seconds"],
        )
    return "Required CRDs present"


@task
def ensure_gateway_task(args, ctx):
    """Ensure the gateway exists and is programmed"""

    config = ctx.config
    gateway = config.platform["gateway"]
    if not llmd_runtime.resource_exists("gateway", gateway["name"], namespace=gateway["namespace"]):
        if not gateway["create_if_missing"]:
            raise RuntimeError(
                f"Required gateway {gateway['name']} does not exist in {gateway['namespace']}"
            )
        manifest = llmd_runtime.render_gateway(config)
        llmd_runtime.apply_manifest(config.artifact_dir / "src" / "gateway.yaml", manifest)

    def _gateway_programmed() -> bool:
        resource = llmd_runtime.oc_get_json(
            "gateway",
            name=gateway["name"],
            namespace=gateway["namespace"],
        )
        return llmd_runtime.condition_status(resource, "Programmed") == "True"

    llmd_runtime.wait_until(
        f"gateway/{gateway['name']} programmed",
        timeout_seconds=gateway["wait_timeout_seconds"],
        interval_seconds=10,
        predicate=_gateway_programmed,
    )
    return "Gateway ready"


@task
def ensure_test_namespace_task(args, ctx):
    """Ensure the llm_d namespace exists"""

    llmd_runtime.ensure_namespace(
        ctx.config.namespace,
        labels={
            "app.kubernetes.io/managed-by": "forge",
            "forge.openshift.io/project": "llm_d",
        },
    )
    return f"Namespace {ctx.config.namespace} ready"


@task
def cleanup_previous_run_task(args, ctx):
    """Delete leftover llm_d resources from the namespace"""

    config = ctx.config
    inference_service_name = config.platform["inference_service"]["name"]
    namespace = config.namespace
    cleanup_timeout_seconds = config.platform["cluster"]["cleanup_timeout_seconds"]
    benchmark_names = {"guidellm-benchmark"}
    if config.benchmark:
        benchmark_names.add(config.benchmark["job_name"])

    shell.run(
        f"oc delete llminferenceservice {inference_service_name} "
        f"-n {namespace} --ignore-not-found=true",
        check=False,
    )

    for benchmark_name in sorted(benchmark_names):
        shell.run(
            f"oc delete job,pvc {benchmark_name} -n {namespace} --ignore-not-found=true",
            check=False,
        )
        shell.run(
            f"oc delete pod {benchmark_name}-copy -n {namespace} --ignore-not-found=true",
            check=False,
        )

    shell.run(
        f'oc delete job -n {namespace} -l "forge.openshift.io/project=llm_d" '
        "--ignore-not-found=true",
        check=False,
    )
    shell.run(
        f'oc delete pod -n {namespace} -l "forge.openshift.io/project=llm_d" '
        "--ignore-not-found=true",
        check=False,
    )
    shell.run(
        f"oc delete pvc -n {namespace} "
        '-l "forge.openshift.io/project=llm_d,forge.openshift.io/preserve!=true" '
        "--ignore-not-found=true",
        check=False,
    )

    llmd_runtime.wait_until(
        f"llminferenceservice/{inference_service_name} deletion in {namespace}",
        timeout_seconds=cleanup_timeout_seconds,
        interval_seconds=10,
        predicate=lambda: not llmd_runtime.resource_exists(
            "llminferenceservice", inference_service_name, namespace=namespace
        ),
    )

    llmd_runtime.wait_until(
        f"llm-d workload pods deletion in {namespace}",
        timeout_seconds=cleanup_timeout_seconds,
        interval_seconds=10,
        predicate=lambda: not (
            pods := llmd_runtime.oc_get_json(
                "pods",
                namespace=namespace,
                selector=f"app.kubernetes.io/name={inference_service_name}",
                ignore_not_found=True,
            )
        )
        or not pods.get("items"),
    )
    return f"Previous llm_d leftovers deleted from {ctx.config.namespace}"


@task
def prepare_model_cache_task(args, ctx):
    """Prepare the shared model cache if enabled"""

    cache_inputs = phase_inputs.prepare_model_cache_inputs_from_prepare(ctx.config)
    cache_spec = llmd_runtime.resolve_model_cache(cache_inputs)
    if not cache_spec:
        LOGGER.info("Model cache disabled for preset=%s", cache_inputs.preset_name)
        return "Model cache disabled"

    if cache_inputs.namespace_is_managed:
        LOGGER.warning(
            "Model cache PVC %s lives in managed namespace %s. Namespace cleanup will remove it; cache reuse requires a stable namespace override.",
            cache_spec.pvc_name,
            cache_spec.namespace,
        )

    prepare_model_cache.ensure_model_cache_pvc(cache_inputs, cache_spec)
    if llmd_runtime.model_cache_pvc_ready(cache_spec):
        LOGGER.info(
            "Model cache PVC %s already contains %s; skipping download",
            cache_spec.pvc_name,
            cache_spec.source_uri,
        )
        prepare_model_cache.capture_model_cache_state(cache_inputs, cache_spec)
        return "Model cache already populated"

    prepare_model_cache.run_model_cache_download_job(cache_inputs, cache_spec)
    llmd_runtime.annotate_model_cache_pvc(cache_spec)
    prepare_model_cache.capture_model_cache_state(cache_inputs, cache_spec)
    return "Model cache prepared"


@task
def verify_gpu_nodes_task(args, ctx):
    """Verify that GPU nodes are available on the cluster"""

    selector = ctx.config.platform["cluster"]["gpu_node_label_selector"]
    data = llmd_runtime.oc_get_json("nodes", selector=selector, ignore_not_found=True)
    items = data.get("items", []) if data else []
    if not items:
        raise RuntimeError(
            f"No GPU nodes found with selector {selector}. The llm_d smoke path requires GPUs."
        )
    return "GPU nodes detected"


@task
def capture_prepare_state_task(args, ctx):
    """Capture cluster state after the prepare phase"""

    config = ctx.config
    artifacts_dir = config.artifact_dir / "artifacts"
    rhoai = config.platform["rhoai"]
    gateway = config.platform["gateway"]

    capture_resource_yaml(
        "datasciencecluster",
        rhoai["datasciencecluster_name"],
        rhoai["namespace"],
        artifacts_dir / "datasciencecluster.yaml",
    )
    capture_resource_yaml(
        "gateway",
        gateway["name"],
        gateway["namespace"],
        artifacts_dir / "gateway.yaml",
    )
    gateway_service = llmd_runtime.oc(
        "get",
        "service",
        "-A",
        "-l",
        f"gateway.networking.k8s.io/gateway-name={gateway['name']}",
        "-o",
        "yaml",
        check=False,
        capture_output=True,
    )
    if gateway_service.returncode == 0 and gateway_service.stdout:
        llmd_runtime.write_text(artifacts_dir / "gateway.service.yaml", gateway_service.stdout)
    if config.platform["artifacts"]["capture_namespace_events"]:
        capture_namespace_events(config.namespace, artifacts_dir / "namespace.events.txt")
    return "Prepare-state artifacts captured"


def verify_oc_access() -> None:
    llmd_runtime.oc("whoami", capture_output=True)


def verify_cluster_version(config: phase_inputs.PrepareInputs) -> None:
    version_info = llmd_runtime.oc("version", "-o", "json", capture_output=True)
    payload = json.loads(version_info.stdout)

    openshift_version = (
        payload.get("openshiftVersion")
        or payload.get("serverVersion", {}).get("gitVersion")
        or payload.get("serverVersion", {}).get("platform")
    )
    if not openshift_version:
        raise RuntimeError("Could not determine OpenShift version from `oc version -o json`")

    minimum = config.platform["cluster"]["minimum_openshift_version"]
    if llmd_runtime.version_tuple(openshift_version) < llmd_runtime.version_tuple(minimum):
        raise RuntimeError(
            f"Cluster version {openshift_version} is older than the llm_d minimum {minimum}"
        )


def ensure_operator_subscription(operator_spec: dict[str, str]) -> dict[str, object]:
    llmd_runtime.ensure_subscription(operator_spec)
    return llmd_runtime.wait_for_operator_csv(
        operator_spec["package"],
        operator_spec["namespace"],
        timeout_seconds=operator_spec["wait_timeout_seconds"],
    )


def prepare_cert_manager(config: phase_inputs.PrepareInputs) -> None:
    operator_spec = llmd_runtime.operator_spec_by_package(
        config.platform, "openshift-cert-manager-operator"
    )
    ensure_operator_subscription(operator_spec)


def prepare_leader_worker_set(config: phase_inputs.PrepareInputs) -> None:
    operator_spec = llmd_runtime.operator_spec_by_package(config.platform, "leader-worker-set")
    ensure_operator_subscription(operator_spec)


def prepare_nfd(config: phase_inputs.PrepareInputs) -> None:
    operator_spec = llmd_runtime.operator_spec_by_package(config.platform, "nfd")
    ensure_operator_subscription(operator_spec)
    llmd_runtime.wait_for_crd(
        operator_spec["bootstrap_crd"],
        timeout_seconds=operator_spec["wait_timeout_seconds"],
    )

    manifest = llmd_runtime.load_manifest_template(config, operator_spec["bootstrap_manifest"])
    nfd_name = manifest["metadata"]["name"]
    nfd_namespace = manifest["metadata"]["namespace"]
    if llmd_runtime.resource_exists("nodefeaturediscovery", nfd_name, namespace=nfd_namespace):
        LOGGER.info(
            "NodeFeatureDiscovery/%s already exists in %s; verifying GPU discovery labels",
            nfd_name,
            nfd_namespace,
        )
    else:
        llmd_runtime.apply_manifest(
            config.artifact_dir / "src" / "nfd-nodefeaturediscovery.yaml",
            manifest,
        )

    llmd_runtime.wait_until(
        "NodeFeatureDiscovery bootstrap resource",
        timeout_seconds=operator_spec["wait_timeout_seconds"],
        interval_seconds=10,
        predicate=lambda: llmd_runtime.resource_exists(
            "nodefeaturediscovery",
            nfd_name,
            namespace=nfd_namespace,
        ),
    )

    wait_for_nfd_gpu_labels(config, timeout_seconds=operator_spec["wait_timeout_seconds"])


def prepare_gpu_operator(config: phase_inputs.PrepareInputs) -> None:
    operator_spec = llmd_runtime.operator_spec_by_package(config.platform, "gpu-operator-certified")
    ensure_operator_subscription(operator_spec)
    llmd_runtime.wait_for_crd(
        operator_spec["bootstrap_crd"],
        timeout_seconds=operator_spec["wait_timeout_seconds"],
    )

    manifest = llmd_runtime.load_manifest_template(config, operator_spec["bootstrap_manifest"])
    clusterpolicy_name = manifest["metadata"]["name"]
    if llmd_runtime.resource_exists("clusterpolicy", clusterpolicy_name):
        LOGGER.info(
            "ClusterPolicy/%s already exists; verifying readiness instead of applying bootstrap manifest",
            clusterpolicy_name,
        )
        wait_for_gpu_clusterpolicy_ready(
            clusterpolicy_name,
            timeout_seconds=operator_spec["wait_timeout_seconds"],
        )
        return

    llmd_runtime.apply_manifest(
        config.artifact_dir / "src" / "gpu-clusterpolicy.yaml",
        manifest,
    )

    wait_for_gpu_clusterpolicy_ready(
        clusterpolicy_name,
        timeout_seconds=operator_spec["wait_timeout_seconds"],
    )


def wait_for_gpu_clusterpolicy_ready(clusterpolicy_name: str, *, timeout_seconds: int) -> None:
    def _clusterpolicy_ready() -> bool:
        payload = llmd_runtime.oc_get_json(
            "clusterpolicy",
            name=clusterpolicy_name,
        )
        state = payload.get("status", {}).get("state", "")
        return state.lower() == "ready"

    llmd_runtime.wait_until(
        f"clusterpolicy/{clusterpolicy_name} ready",
        timeout_seconds=timeout_seconds,
        interval_seconds=15,
        predicate=_clusterpolicy_ready,
    )


def prepare_rhoai_operator(config: phase_inputs.PrepareInputs) -> None:
    operator_spec = llmd_runtime.operator_spec_by_package(config.platform, "rhods-operator")
    ensure_operator_subscription(operator_spec)
    ensure_required_crds(config.platform["rhoai"]["required_crds_before_dsc"], config)


def ensure_required_crds(crd_names: list[str], config: phase_inputs.PrepareInputs) -> None:
    for crd_name in crd_names:
        llmd_runtime.wait_for_crd(
            crd_name,
            timeout_seconds=config.platform["rhoai"]["wait_timeout_seconds"],
        )


def apply_datasciencecluster(config: phase_inputs.PrepareInputs) -> None:
    manifest = llmd_runtime.render_datasciencecluster(config)
    llmd_runtime.apply_manifest(config.artifact_dir / "src" / "datasciencecluster.yaml", manifest)
    llmd_runtime.oc(
        "get",
        "datasciencecluster",
        config.platform["rhoai"]["datasciencecluster_name"],
        "-n",
        config.platform["rhoai"]["namespace"],
        "-o",
        "yaml",
        capture_output=True,
    )


def wait_for_datasciencecluster_ready(config: phase_inputs.PrepareInputs) -> None:
    rhoai = config.platform["rhoai"]

    def _dsc_ready() -> bool:
        payload = llmd_runtime.oc_get_json(
            "datasciencecluster",
            name=rhoai["datasciencecluster_name"],
            namespace=rhoai["namespace"],
        )
        phase = payload.get("status", {}).get("phase")
        if phase == "Ready":
            return True
        if phase in {"Failed", "Error"}:
            raise RuntimeError(f"DataScienceCluster entered terminal phase {phase}")
        return False

    llmd_runtime.wait_until(
        f"datasciencecluster/{rhoai['datasciencecluster_name']} ready",
        timeout_seconds=rhoai["wait_timeout_seconds"],
        interval_seconds=10,
        predicate=_dsc_ready,
    )


def ensure_gateway(config: phase_inputs.PrepareInputs) -> None:
    gateway = config.platform["gateway"]
    if not llmd_runtime.resource_exists("gateway", gateway["name"], namespace=gateway["namespace"]):
        if not gateway["create_if_missing"]:
            raise RuntimeError(
                f"Required gateway {gateway['name']} does not exist in {gateway['namespace']}"
            )
        manifest = llmd_runtime.render_gateway(config)
        llmd_runtime.apply_manifest(config.artifact_dir / "src" / "gateway.yaml", manifest)

    def _gateway_programmed() -> bool:
        resource = llmd_runtime.oc_get_json(
            "gateway",
            name=gateway["name"],
            namespace=gateway["namespace"],
        )
        return llmd_runtime.condition_status(resource, "Programmed") == "True"

    llmd_runtime.wait_until(
        f"gateway/{gateway['name']} programmed",
        timeout_seconds=gateway["wait_timeout_seconds"],
        interval_seconds=10,
        predicate=_gateway_programmed,
    )


def ensure_test_namespace(config: phase_inputs.PrepareInputs) -> None:
    llmd_runtime.ensure_namespace(
        config.namespace,
        labels={
            "app.kubernetes.io/managed-by": "forge",
            "forge.openshift.io/project": "llm_d",
        },
    )


def verify_gpu_nodes(config: phase_inputs.PrepareInputs) -> None:
    selector = config.platform["cluster"]["gpu_node_label_selector"]
    data = llmd_runtime.oc_get_json("nodes", selector=selector, ignore_not_found=True)
    items = data.get("items", []) if data else []
    if not items:
        raise RuntimeError(
            f"No GPU nodes found with selector {selector}. The llm_d smoke path requires GPUs."
        )


def wait_for_nfd_gpu_labels(config: phase_inputs.PrepareInputs, *, timeout_seconds: int) -> None:
    selectors = config.platform["cluster"]["nfd_gpu_detection_labels"]

    def _labels_present() -> bool:
        for selector in selectors:
            data = llmd_runtime.oc_get_json("nodes", selector=selector, ignore_not_found=True)
            if data and data.get("items"):
                return True
        return False

    llmd_runtime.wait_until(
        "NFD GPU discovery labels on cluster nodes",
        timeout_seconds=timeout_seconds,
        interval_seconds=15,
        predicate=_labels_present,
    )


def capture_prepare_state(config: phase_inputs.PrepareInputs) -> None:
    artifacts_dir = config.artifact_dir / "artifacts"
    rhoai = config.platform["rhoai"]
    gateway = config.platform["gateway"]

    capture_resource_yaml(
        "datasciencecluster",
        rhoai["datasciencecluster_name"],
        rhoai["namespace"],
        artifacts_dir / "datasciencecluster.yaml",
    )
    capture_resource_yaml(
        "gateway",
        gateway["name"],
        gateway["namespace"],
        artifacts_dir / "gateway.yaml",
    )
    gateway_service = llmd_runtime.oc(
        "get",
        "service",
        "-A",
        "-l",
        f"gateway.networking.k8s.io/gateway-name={gateway['name']}",
        "-o",
        "yaml",
        check=False,
        capture_output=True,
    )
    if gateway_service.returncode == 0 and gateway_service.stdout:
        llmd_runtime.write_text(artifacts_dir / "gateway.service.yaml", gateway_service.stdout)
    if config.platform["artifacts"]["capture_namespace_events"]:
        capture_namespace_events(config.namespace, artifacts_dir / "namespace.events.txt")


def capture_resource_yaml(
    kind: str,
    name: str,
    namespace: str,
    destination: Path,
    *,
    check: bool = True,
) -> None:
    result = llmd_runtime.oc(
        "get",
        kind,
        name,
        "-n",
        namespace,
        "-o",
        "yaml",
        check=check,
        capture_output=True,
    )
    if result.returncode == 0 and result.stdout:
        llmd_runtime.write_text(destination, result.stdout)


def capture_namespace_events(namespace: str, destination: Path) -> None:
    result = llmd_runtime.oc(
        "get",
        "events",
        "-n",
        namespace,
        "--sort-by=.metadata.creationTimestamp",
        check=False,
        capture_output=True,
    )
    if result.returncode == 0 and result.stdout:
        llmd_runtime.write_text(destination, result.stdout)


main = toolbox.create_toolbox_main(run)


if __name__ == "__main__":
    main()
