#!/usr/bin/env python3

from __future__ import annotations

from dataclasses import replace

from projects.core.dsl import execute_tasks, task, toolbox
from projects.llm_d.runtime import llmd_runtime, phase_inputs


def run(*, inputs_file: str) -> int:
    """
    Ensure the llm_d gateway exists and is programmed.

    Args:
        inputs_file: Path to the prepare phase input file generated by orchestration
    """

    llmd_runtime.init()
    execute_tasks(locals())
    return 0


@task
def load_inputs(args, ctx):
    """Load prepare inputs into the command-local artifact directory"""

    ctx.config = replace(
        phase_inputs.load_prepare_inputs(args.inputs_file),
        artifact_dir=args.artifact_dir,
    )
    return f"Loaded gateway inputs for namespace {ctx.config.namespace}"


@task
def ensure_gateway(args, ctx):
    """Ensure the gateway exists and reaches Programmed=True"""

    config = ctx.config
    gateway = config.platform["gateway"]
    if not llmd_runtime.resource_exists("gateway", gateway["name"], namespace=gateway["namespace"]):
        if not gateway["create_if_missing"]:
            raise RuntimeError(
                f"Required gateway {gateway['name']} does not exist in {gateway['namespace']}"
            )
        manifest = llmd_runtime.render_gateway(config)
        llmd_runtime.apply_manifest(config.artifact_dir / "src" / "gateway.yaml", manifest)

    def _gateway_programmed() -> bool:
        resource = llmd_runtime.oc_get_json(
            "gateway",
            name=gateway["name"],
            namespace=gateway["namespace"],
        )
        return llmd_runtime.condition_status(resource, "Programmed") == "True"

    llmd_runtime.wait_until(
        f"gateway/{gateway['name']} programmed",
        timeout_seconds=gateway["wait_timeout_seconds"],
        interval_seconds=10,
        predicate=_gateway_programmed,
    )
    return "Gateway ready"


main = toolbox.create_toolbox_main(run)


if __name__ == "__main__":
    main()
