#!/usr/bin/env python3

from __future__ import annotations

from projects.core.dsl import execute_tasks, shell, task, toolbox
from projects.llm_d.orchestration import llmd_runtime, phase_inputs


def run(*, inputs_file: str) -> int:
    """Delete llm_d runtime leftovers from a namespace.

    Args:
        inputs_file: Path to the cleanup phase input file generated by orchestration
    """

    llmd_runtime.init()
    execute_tasks(locals())
    return 0


@task
def load_inputs(args, ctx):
    """Load the cleanup phase inputs"""

    ctx.inputs = phase_inputs.load_cleanup_inputs(args.inputs_file)
    return f"Loaded cleanup inputs for namespace {ctx.inputs.namespace}"


@task
def delete_leftovers(args, ctx):
    """Delete llm_d runtime leftovers"""

    inputs = ctx.inputs
    if not llmd_runtime.resource_exists("namespace", inputs.namespace):
        return f"Namespace {inputs.namespace} does not exist; nothing to clean"

    inference_service_name = inputs.platform["inference_service"]["name"]
    namespace = inputs.namespace
    cleanup_timeout_seconds = inputs.platform["cluster"]["cleanup_timeout_seconds"]
    benchmark_names = {"guidellm-benchmark"}
    if inputs.benchmark:
        benchmark_names.add(inputs.benchmark["job_name"])

    shell.run(
        f"oc delete llminferenceservice {inference_service_name} "
        f"-n {namespace} --ignore-not-found=true",
        check=False,
    )

    for benchmark_name in sorted(benchmark_names):
        shell.run(
            f"oc delete job,pvc {benchmark_name} -n {namespace} --ignore-not-found=true",
            check=False,
        )
        shell.run(
            f"oc delete pod {benchmark_name}-copy -n {namespace} --ignore-not-found=true",
            check=False,
        )

    shell.run(
        f'oc delete job -n {namespace} -l "forge.openshift.io/project=llm_d" '
        "--ignore-not-found=true",
        check=False,
    )
    shell.run(
        f'oc delete pod -n {namespace} -l "forge.openshift.io/project=llm_d" '
        "--ignore-not-found=true",
        check=False,
    )
    shell.run(
        f"oc delete pvc -n {namespace} "
        '-l "forge.openshift.io/project=llm_d,forge.openshift.io/preserve!=true" '
        "--ignore-not-found=true",
        check=False,
    )

    llmd_runtime.wait_until(
        f"llminferenceservice/{inference_service_name} deletion in {namespace}",
        timeout_seconds=cleanup_timeout_seconds,
        interval_seconds=10,
        predicate=lambda: not llmd_runtime.resource_exists(
            "llminferenceservice", inference_service_name, namespace=namespace
        ),
    )

    llmd_runtime.wait_until(
        f"llm-d workload pods deletion in {namespace}",
        timeout_seconds=cleanup_timeout_seconds,
        interval_seconds=10,
        predicate=lambda: _llm_d_pods_gone(namespace, inference_service_name),
    )

    return f"Cleanup finished for namespace {namespace}"


def delete_run_leftovers(inputs: phase_inputs.CleanupInputs) -> None:
    if not llmd_runtime.resource_exists("namespace", inputs.namespace):
        return

    inference_service_name = inputs.platform["inference_service"]["name"]
    namespace = inputs.namespace
    cleanup_timeout_seconds = inputs.platform["cluster"]["cleanup_timeout_seconds"]
    benchmark_names = {"guidellm-benchmark"}
    if inputs.benchmark:
        benchmark_names.add(inputs.benchmark["job_name"])

    shell.run(
        f"oc delete llminferenceservice {inference_service_name} "
        f"-n {namespace} --ignore-not-found=true",
        check=False,
    )

    for benchmark_name in sorted(benchmark_names):
        shell.run(
            f"oc delete job,pvc {benchmark_name} -n {namespace} --ignore-not-found=true",
            check=False,
        )
        shell.run(
            f"oc delete pod {benchmark_name}-copy -n {namespace} --ignore-not-found=true",
            check=False,
        )

    shell.run(
        f'oc delete job -n {namespace} -l "forge.openshift.io/project=llm_d" '
        "--ignore-not-found=true",
        check=False,
    )
    shell.run(
        f'oc delete pod -n {namespace} -l "forge.openshift.io/project=llm_d" '
        "--ignore-not-found=true",
        check=False,
    )
    shell.run(
        f"oc delete pvc -n {namespace} "
        '-l "forge.openshift.io/project=llm_d,forge.openshift.io/preserve!=true" '
        "--ignore-not-found=true",
        check=False,
    )

    llmd_runtime.wait_until(
        f"llminferenceservice/{inference_service_name} deletion in {namespace}",
        timeout_seconds=cleanup_timeout_seconds,
        interval_seconds=10,
        predicate=lambda: not llmd_runtime.resource_exists(
            "llminferenceservice", inference_service_name, namespace=namespace
        ),
    )

    llmd_runtime.wait_until(
        f"llm-d workload pods deletion in {namespace}",
        timeout_seconds=cleanup_timeout_seconds,
        interval_seconds=10,
        predicate=lambda: _llm_d_pods_gone(namespace, inference_service_name),
    )


def _llm_d_pods_gone(namespace: str, inference_service_name: str) -> bool:
    payload = llmd_runtime.oc_get_json(
        "pods",
        namespace=namespace,
        selector=f"app.kubernetes.io/name={inference_service_name}",
        ignore_not_found=True,
    )
    return not payload or not payload.get("items")


main = toolbox.create_toolbox_main(run)


if __name__ == "__main__":
    main()
