#!/usr/bin/env python3

from __future__ import annotations

from dataclasses import replace

from projects.core.dsl import execute_tasks, task, toolbox
from projects.llm_d.runtime import llmd_runtime, phase_inputs


def run(*, inputs_file: str) -> int:
    """
    Wait for the llm_d DataScienceCluster to become ready.

    Args:
        inputs_file: Path to the prepare phase input file generated by orchestration
    """

    llmd_runtime.init()
    execute_tasks(locals())
    return 0


@task
def load_inputs(args, ctx):
    """Load prepare inputs into the command-local artifact directory"""

    ctx.config = replace(
        phase_inputs.load_prepare_inputs(args.inputs_file),
        artifact_dir=args.artifact_dir,
    )
    return f"Loaded DataScienceCluster wait inputs for namespace {ctx.config.namespace}"


@task
def wait_for_datasciencecluster_ready(args, ctx):
    """Wait for the DataScienceCluster phase to become Ready"""

    rhoai = ctx.config.platform["rhoai"]

    def _dsc_ready() -> bool:
        payload = llmd_runtime.oc_get_json(
            "datasciencecluster",
            name=rhoai["datasciencecluster_name"],
            namespace=rhoai["namespace"],
        )
        phase = payload.get("status", {}).get("phase")
        if phase == "Ready":
            return True
        if phase in {"Failed", "Error"}:
            raise RuntimeError(f"DataScienceCluster entered terminal phase {phase}")
        return False

    llmd_runtime.wait_until(
        f"datasciencecluster/{rhoai['datasciencecluster_name']} ready",
        timeout_seconds=rhoai["wait_timeout_seconds"],
        interval_seconds=10,
        predicate=_dsc_ready,
    )
    return "DataScienceCluster ready"


main = toolbox.create_toolbox_main(run)


if __name__ == "__main__":
    main()
