apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: forge-core
  labels:
    app: forge
    component: image-build
  annotations:
    description: "FORGE core image for remote job execution"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/rh_perfscale/forge:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
