apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - forge-development.yaml
  - forge-production.yaml

commonLabels:
  app.kubernetes.io/name: forge-on-fournos
  app.kubernetes.io/part-of: fournos
