#!/usr/bin/env python3

from __future__ import annotations

import logging

from projects.core.dsl import always, execute_tasks, shell, task, toolbox
from projects.llm_d.runtime import llmd_runtime, phase_inputs
from projects.llm_d.toolbox.capture_llmisvc_state import main as capture_llmisvc_state
from projects.llm_d.toolbox.deploy_llmisvc import main as deploy_llmisvc
from projects.llm_d.toolbox.run_guidellm_benchmark import main as run_guidellm_benchmark_command
from projects.llm_d.toolbox.run_smoke_request import main as run_smoke_request_command

LOGGER = logging.getLogger(__name__)


def run(*, inputs_file: str) -> int:
    """Deploy llm_d, run the smoke request, and optionally execute GuideLLM.

    Args:
        inputs_file: Path to the test phase input file generated by orchestration
    """

    llmd_runtime.init()
    execute_tasks(locals())
    return 0


@task
def load_inputs(args, ctx):
    """Load the test phase inputs"""

    ctx.config = phase_inputs.load_test_inputs(args.inputs_file)
    return f"Loaded test inputs for preset {ctx.config.preset_name}"


@task
def deploy_inference_service_task(args, ctx):
    """Deploy the LLMInferenceService and resolve its endpoint"""

    ctx.endpoint_url = deploy_llmisvc.run(
        inputs_file=args.inputs_file,
    )
    return f"Endpoint resolved: {ctx.endpoint_url}"


@task
def run_smoke_request_task(args, ctx):
    """Run the smoke request against the deployed service"""

    ctx.smoke_response = run_smoke_request_command.run(
        inputs_file=args.inputs_file,
        endpoint_url=ctx.endpoint_url,
    )
    return "Smoke request completed"


@task
def run_guidellm_benchmark_task(args, ctx):
    """Run the GuideLLM benchmark when enabled for the preset"""

    if not ctx.config.benchmark:
        return "GuideLLM benchmark disabled"

    run_guidellm_benchmark_command.run(
        inputs_file=args.inputs_file,
        endpoint_url=ctx.endpoint_url,
    )
    return f"GuideLLM benchmark {ctx.config.benchmark['job_name']} completed"


@always
@task
def capture_inference_service_state_task(args, ctx):
    """Capture the LLMInferenceService state and related resources"""

    config = getattr(ctx, "config", None)
    if not config:
        return "Test inputs unavailable; skipping state capture"

    capture_llmisvc_state.run(
        llmisvc_name=config.platform["inference_service"]["name"],
        namespace=config.namespace,
    )
    return "Inference-service artifacts captured"


@always
@task
def write_endpoint_url_task(args, ctx):
    """Persist the resolved endpoint URL when available"""

    config = getattr(ctx, "config", None)
    if not config:
        return "Test inputs unavailable; skipping endpoint capture"

    endpoint_url = getattr(ctx, "endpoint_url", None)
    if not endpoint_url:
        return "Endpoint URL not available"

    llmd_runtime.write_text(config.artifact_dir / "artifacts" / "endpoint.url", f"{endpoint_url}\n")
    return "Endpoint URL captured"


@always
@task
def cleanup_runtime_resources_task(args, ctx):
    """Delete smoke and benchmark helper resources"""

    config = getattr(ctx, "config", None)
    if not config:
        return "Test inputs unavailable; skipping cleanup"

    benchmark_name = config.benchmark["job_name"] if config.benchmark else "guidellm-benchmark"
    smoke_job_name = config.platform["smoke"]["job_name"]
    namespace = config.namespace

    llmd_runtime.oc(
        "delete",
        "job",
        smoke_job_name,
        "-n",
        namespace,
        "--ignore-not-found=true",
        check=False,
    )
    llmd_runtime.oc(
        "delete",
        "job,pvc",
        benchmark_name,
        "-n",
        namespace,
        "--ignore-not-found=true",
        check=False,
    )
    llmd_runtime.oc(
        "delete",
        "pod",
        f"{benchmark_name}-copy",
        "-n",
        namespace,
        "--ignore-not-found=true",
        check=False,
    )
    return "Test helper resources deleted"


@always
@task
def capture_namespace_events_task(args, ctx):
    """Capture namespace events after the test run"""

    config = getattr(ctx, "config", None)
    if not config:
        return "Test inputs unavailable; skipping namespace events capture"

    shell.run(
        f"oc get events -n {config.namespace} --sort-by=.metadata.creationTimestamp",
        check=False,
        stdout_dest=config.artifact_dir / "artifacts" / "namespace.events.txt",
    )
    return "Namespace events captured"


main = toolbox.create_toolbox_main(run)


if __name__ == "__main__":
    main()
