#!/usr/bin/env python3

from __future__ import annotations

from dataclasses import replace

from projects.core.dsl import execute_tasks, task, toolbox
from projects.llm_d.runtime import llmd_runtime, phase_inputs, test_flow


def run(*, inputs_file: str, endpoint_url: str) -> dict[str, object]:
    """
    Run the llm_d smoke request job against a resolved endpoint.

    Args:
        inputs_file: Path to the test phase input file generated by orchestration
        endpoint_url: Gateway endpoint URL returned by the deploy command
    """

    llmd_runtime.init()
    context = execute_tasks(locals())
    return context.response


@task
def load_inputs(args, ctx):
    """Load the test inputs into the command-local artifact directory"""

    ctx.config = replace(
        phase_inputs.load_test_inputs(args.inputs_file),
        artifact_dir=args.artifact_dir,
    )
    return f"Loaded smoke inputs for namespace {ctx.config.namespace}"


@task
def run_smoke_request_task(args, ctx):
    """Run the smoke request job and validate its response"""

    ctx.response = test_flow.run_smoke_request(ctx.config, args.endpoint_url)
    return "Smoke request completed"


main = toolbox.create_toolbox_main(run)


if __name__ == "__main__":
    main()
