#!/usr/bin/env python3

from __future__ import annotations

from dataclasses import replace

from projects.core.dsl import execute_tasks, task, toolbox
from projects.llm_d.runtime import llmd_runtime, phase_inputs, test_flow


def run(*, inputs_file: str) -> str:
    """
    Deploy the llm_d LLMInferenceService and wait for its endpoint.

    Args:
        inputs_file: Path to the test phase input file generated by orchestration
    """

    llmd_runtime.init()
    context = execute_tasks(locals())
    return context.endpoint_url


@task
def load_inputs(args, ctx):
    """Load the test inputs into the command-local artifact directory"""

    ctx.config = replace(
        phase_inputs.load_test_inputs(args.inputs_file),
        artifact_dir=args.artifact_dir,
    )
    return f"Loaded llm_d deploy inputs for namespace {ctx.config.namespace}"


@task
def deploy_llmisvc_task(args, ctx):
    """Deploy the llm_d inference service and resolve its endpoint"""

    ctx.endpoint_url = test_flow.deploy_llmisvc(ctx.config)
    return f"Endpoint resolved: {ctx.endpoint_url}"


main = toolbox.create_toolbox_main(run)


if __name__ == "__main__":
    main()
